apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: scaledobject-creator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaledobject-creator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaledobject-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scaledobject-creator
subjects:
- kind: ServiceAccount
  name: scaledobject-creator
  namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scaledobject-creator
  namespace: kube-system
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scaledobject-creator
            image: ghcr.io/alfianabdi/scaledobject-creator:116efb
            imagePullPolicy: IfNotPresent
            args:
            - --excluded-namespace=aws-load-balancer-controller,calico-apiserver,calico-system,cert-manager,descheduler,external-dns,ingress-nginx,karpenter,keda,kube-system,logging,monitoring,observability,opentelemetry,rabbitmq-system,tigera-operator
          restartPolicy: OnFailure
          serviceAccount: scaledobject-creator
          serviceAccountName: scaledobject-creator
